apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mosip-infra
  description: Infrastructure repository for MOSIP deployment by Infosys
  annotations:
    github.com/project-slug: Infosys/mosip-infra
    backstage.io/techdocs-ref: dir:.
  tags: [mosip, infrastructure, deployment]
spec:
  type: infrastructure
  lifecycle: production
  owner: group:admin-group 
  ownedBy: [group:ADMCOE-Team, group:admin-group, group:dev-group]
  dependsOn: []
  system: "mosip-platform"

